---
title: "Non Differentiality Test"
date: "16/03/2022"
output: 
  rmdformats::downcute:
  toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(data.table)
library(ggplot2)
library(plotly)
library(ggthemes)
```

<br><br><br>

## Agenda

- Non-Differentility test: conditional data simulation
  
- Pregnancy: predictive model 

- BRAHMS: PPV confidence interval


<br><br><br>

## Non-Differentility test

```{r params, echo=TRUE}
### starting parameters
N        <- 200000
prop_exp <- 0.2
pi_ne    <- 0.05
risk     <- 2
pi_e     <- pi_ne*risk


### validation indices: SE_AUB
SE_AUB           <- 0.90

### validation indices: E=1 & Y=1
SE_A_e           <- 0.5
SE_B_given_A_e   <- 0.8
 
SE_A_int_B_e       <- SE_A_e * SE_B_given_A_e
SE_B_e             <- SE_AUB - SE_A_e + SE_A_int_B_e
SE_A_given_B_e     <- SE_A_int_B_e / SE_B_e
SE_B_given_not_A_e <- (SE_B_e - SE_A_int_B_e) / (1 - SE_A_e)
  
### validation indices: E=0 & Y=1
SE_A_ne          <- 0.5
SE_B_given_A_ne  <- 0.8

SE_A_int_B_ne       <- SE_A_ne * SE_B_given_A_ne
SE_B_ne             <- SE_AUB - SE_A_ne + SE_A_int_B_ne
SE_A_given_B_ne     <- SE_A_int_B_ne / SE_B_ne
SE_B_given_not_A_ne <- (SE_B_ne - SE_A_int_B_ne) / (1 - SE_A_ne)

### validation indices: E=1 & Y=0
SP_A_e           <- 0.99
SP_B_e           <- 0.90

### validation indices: E=0 & Y=0
SP_A_ne          <- 0.99
SP_B_ne          <- 0.90


### Bootstrap parameters
na    = 250  # A sample size
nb    = 250  # B sample size
nsam  = 1000 # Monte Carlo rep
nboot = 500  # Bootstrap sample size
```


```{r graph, echo=FALSE}
Result <- fread("H:/Seafile/Mia Libreria/GitHub_Repo/NonDifferentialityTest/Rscript/05_Results/DT_for_plot.csv")
plot <- ggplot(Result, aes(x=se_e, y=Power, col = Scenario))+ #, label=label
  geom_point()+
  geom_line(size=1)+
  theme_hc()+
  ylab("")+
  #scale_color_manual(values = c("deeppink", "skyblue3", "yellow3"))+
  #scale_x_continuous( breaks=se_e, labels=se_e)+
  geom_vline(xintercept = 0.4, lty= 2, col = "slategrey")+
  geom_vline(xintercept = 0.6, lty= 2, col = "slategrey")
  #geom_label_repel(aes(label = label),
  #                 box.padding   = 0.35, 
  #                 point.padding = 0.5,
  #                 segment.color = 'slategrey')

ploty <- ggplotly(plot)
ploty
```

## Pregnancy

## BRAHMS